openapi: 3.0.1
info:
  contact:
    email: henryxm@163.com
    name: 内测云分发开发者API接口
    url: https://neice.cloud
  description: 内测云开发者服务平台应用程序接口文档
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: https://neice.cloud
  title: 内测云分发开发者API接口
  version: 1.0.0
servers:
- url: https://neice.cloud/
tags:
- description: 用户余额
  name: balance
- description: iOS设备注册
  name: device
- description: 获取签名节点入口
  name: endpoint
- description: 客户端授权登录认证获取Token接口
  name: oauth
paths:
  /api/aas/v1/certificate:
    post:
      description: 获取iOS设备证书
      operationId: getCertificate
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: udid
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OutResponseOfPersonalCertificate'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取iOS设备证书
      tags:
      - device
      x-codegen-request-body-name: udid
      x-contentType: application/json
      x-accepts: '*/*'
  /api/aas/v1/certificates:
    post:
      description: 获取iOS设备证书列表
      operationId: getCertificates
      parameters:
      - description: asc
        in: query
        name: asc
        schema:
          type: boolean
      - description: limit
        in: query
        name: limit
        required: true
        schema:
          format: int32
          type: integer
      - description: page
        in: query
        name: page
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OutResponseOfListOfPersonalCertificate'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取iOS设备证书列表
      tags:
      - device
      x-accepts: '*/*'
  /api/aas/v1/register:
    post:
      description: iOS设备注册
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRequest'
        description: deviceRequest
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OutResponseOfPersonalCertificate'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: iOS设备注册
      tags:
      - device
      x-codegen-request-body-name: deviceRequest
      x-contentType: application/json
      x-accepts: '*/*'
  /api/user/v1/balance:
    post:
      description: 获取用户余额
      operationId: getBalance
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OutResponseOfBalance'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取用户余额
      tags:
      - balance
      x-accepts: '*/*'
  /endpoint/getEndpoint:
    post:
      description: 获取签名节点入口
      operationId: getEndpoint
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties:
                type: string
              type: object
        description: param
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Endpoint'
                type: array
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取签名节点入口
      tags:
      - endpoint
      x-codegen-request-body-name: param
      x-contentType: application/json
      x-accepts: '*/*'
  /oauth2/token:
    post:
      description: 获取Token
      operationId: getToken
      parameters:
      - description: client_id
        in: query
        name: client_id
        required: true
        schema:
          type: string
      - description: client_secret
        in: query
        name: client_secret
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: 获取Token
      tags:
      - oauth
      x-accepts: '*/*'
  /oauth2/userInfo:
    get:
      description: 获取用户信息
      operationId: getUserInfo
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HttpEntity'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取用户信息
      tags:
      - oauth
      x-accepts: application/json;charset=UTF-8
    post:
      description: 获取用户信息
      operationId: getUserInfo_1
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HttpEntity'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      security:
      - Authorization:
        - global
      summary: 获取用户信息
      tags:
      - oauth
      x-accepts: application/json;charset=UTF-8
components:
  schemas:
    Balance:
      example:
        reward: 1.4658129805029452
        total: 5.962133916683182
        balance: 6.027456183070403
        userUuid: userUuid
      properties:
        balance:
          type: number
        reward:
          type: number
        total:
          type: number
        userUuid:
          type: string
      title: Balance
      type: object
    DeviceRequest:
      example:
        phone: phone
        name: name
        reserve: true
        callback: callback
        udid: udid
        quality: 0
      properties:
        callback:
          description: 预定证书激活时可通过回调地址将证书推送到业务系统中，为空将不会回调
          type: string
        name:
          description: 当调用的预定证书激活时，激活通知短信将发送该名称，方便区分
          type: string
        phone:
          description: 预定手机:设备激活后发送可以安装APP的通知短信
          type: string
        quality:
          description: 增加质保天数后台可能会增加计费
          format: int32
          type: integer
        reserve:
          description: 证书预定参数开关如果卡设备，将在设备处于激活状态时通知用户安装
          type: boolean
        udid:
          description: iOS或iPad设备UDID
          type: string
      required:
      - udid
      title: DeviceRequest
      type: object
    Endpoint:
      example:
        endpoint: endpoint
        name: name
        description: description
      properties:
        description:
          type: string
        endpoint:
          type: string
        name:
          type: string
      title: Endpoint
      type: object
    HttpEntity:
      example:
        body: '{}'
      properties:
        body:
          properties: {}
          type: object
      title: HttpEntity
      type: object
    OutResponseOfBalance:
      example:
        msg: msg
        code: 0
        data:
          reward: 1.4658129805029452
          total: 5.962133916683182
          balance: 6.027456183070403
          userUuid: userUuid
        success: true
      properties:
        code:
          format: int32
          type: integer
        data:
          $ref: '#/components/schemas/Balance'
        msg:
          type: string
        success:
          type: boolean
      title: OutResponseOfBalance
      type: object
    OutResponseOfListOfPersonalCertificate:
      example:
        msg: msg
        code: 0
        data:
        - certificateId: certificateId
          mobileprovision: mobileprovision
          certificate: certificate
          description: description
          deviceId: deviceId
          uuid: uuid
          quality: 1
          valid: true
          password: password
          price: 6.027456183070403
          profileId: profileId
          name: name
          reserve: true
          udid: udid
        - certificateId: certificateId
          mobileprovision: mobileprovision
          certificate: certificate
          description: description
          deviceId: deviceId
          uuid: uuid
          quality: 1
          valid: true
          password: password
          price: 6.027456183070403
          profileId: profileId
          name: name
          reserve: true
          udid: udid
        success: true
      properties:
        code:
          format: int32
          type: integer
        data:
          items:
            $ref: '#/components/schemas/PersonalCertificate'
          type: array
        msg:
          type: string
        success:
          type: boolean
      title: OutResponseOfListOfPersonalCertificate
      type: object
    OutResponseOfPersonalCertificate:
      example:
        msg: msg
        code: 0
        data:
          certificateId: certificateId
          mobileprovision: mobileprovision
          certificate: certificate
          description: description
          deviceId: deviceId
          uuid: uuid
          quality: 1
          valid: true
          password: password
          price: 6.027456183070403
          profileId: profileId
          name: name
          reserve: true
          udid: udid
        success: true
      properties:
        code:
          format: int32
          type: integer
        data:
          $ref: '#/components/schemas/PersonalCertificate'
        msg:
          type: string
        success:
          type: boolean
      title: OutResponseOfPersonalCertificate
      type: object
    PersonalCertificate:
      example:
        certificateId: certificateId
        mobileprovision: mobileprovision
        certificate: certificate
        description: description
        deviceId: deviceId
        uuid: uuid
        quality: 1
        valid: true
        password: password
        price: 6.027456183070403
        profileId: profileId
        name: name
        reserve: true
        udid: udid
      properties:
        certificate:
          description: 设备证书P12
          type: string
        certificateId:
          description: 证书ID
          type: string
        description:
          description: 证书描述信息
          type: string
        deviceId:
          description: 设备ID
          type: string
        mobileprovision:
          description: 设备的描述文件Mobileprovision
          type: string
        name:
          description: 证书名称
          type: string
        password:
          description: 设备证书密码
          type: string
        price:
          description: 服务价格
          type: number
        profileId:
          description: 描述文件ID
          type: string
        quality:
          description: 证书质保天数
          format: int32
          type: integer
        reserve:
          description: 预定证书
          type: boolean
        udid:
          description: 设备的UDID
          type: string
        uuid:
          description: 单个设备证书UUID
          type: string
        valid:
          description: 证书是否有效
          type: boolean
      title: PersonalCertificate
      type: object
  securitySchemes:
    Authorization:
      flows:
        clientCredentials:
          scopes:
            all: All scope is trusted!
          tokenUrl: /oauth2/token
      type: oauth2
x-original-swagger-version: "2.0"

